### ISSUE TITLE
Basic API ideas

### ISSUE THREAD

**Issue by zhammer** [zhammer/smis#2]
#### smis.request
```py
import smis

response = smis.request(
    role='user',
    action='get',
    headers={
        'cache': 'miss'
    },
    body={
        'id': '1234'
    }
)
```

#### smis.message
```py
import smis

smis.message(
    role='user-info',
    action='added',
    body={
        'id': '1234'
    }
)
```

#### smis.SmisResponse
```py
from typing import Dict, NamedTuple, Optional, Union

Primitive = Optional[Union[int, str, float, bool]]

class SmisResponse(NamedTuple):
    status_code: int
    error: str
    body: str

    @property
    def json(self) -> Dict[str, Primitive]:
        return json.dumps(self.body)
```

**Comment by zhammer** [comment]
### sims.yml
```yml
project: morning_cd


services:
  # these could be sourced from local files
  listen-store:
    - handler: morning_cd.services.listen_store.handler:handler
      arn: # arn
      alias: # default = $LATEST
      version: # overrides alias
      handles:
        requests:
          - role: listen-store
            actions:
              - add
              - get
              - list
              
  sunlight:
    - handler: morning_cd.services.sunlight.handler:handler
      arn: # arn
      handles:
        - role: sunlight
          actions:
            - get

  listen-submit:
    - handler: morning_cd.services.listen_submit.handler:handler
      arn: # arn
      handles:
        requests:
          - role: listen-submit
            actions:
              - post

  listen-store-cache:
    - handler: morning_cd.services.listen_store_cache.handler:handler
      arn: # arn
      handles:
        requests:
          - role: listen-store
            actions:
              - add

  playlist-build:
    - handler: morning_cd.services.playlist_build.handler:handler
      arn: # arn
      handles:
        messages:
          - role: playlist-build
            actions:
              - add-listen

router:
  requests:
    - role: listen-store
      - action: add
        service: ${services:listen-store}
      - action: remove
        service: ${services:listen-store}
      - action: get
        services:
          - service: ${services:listen-store}
            match:
              headers:
                - cache:
                    value: miss
          - service: ${services:listen-store-cache}

    - role: listen-submit
      - action: post
        service: ${services:listen-submit}

    - role: sunlight
      - action: get
        service: ${services:sunlight}

  messages:
    - role: playlist-build
      - action: add-listen
        services:
          - service: ${services:playlist-build}
            consume: true
          - service: ???
            # i want messages that fail due to access token to be held in a queue
            # until the admin manually resets their access token
            match:
              headers:
                error: 'invalid access token'
            
          
translator:
  messages:
    - role: listen-info
      - action: added
        to:
          - role: playlist-build
            action: add-listen
```
